version: "3.4"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    container_name: db
    volumes:
      - db-data:/var/lib/sql/data
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Teste1234"
      ACCEPT_EULA: "Y"

volumes:
  db-data:
